### ISSUE TITLE
Add pre-assigned students to workshops before others

### ISSUE THREAD

**Issue by Chris-Pyles** [WhitmanCSCapstone/ge-scheduling#7]
Some students are manually assigned to certain workshop sessions by the client. These matches should be modeled before any normal matches are made.

To make sure that pre-assigned students are not removed from their workshops, they should not be added to the array `Matcher.allStudents`.

**Comment by beszel** [comment]
This is troublesome because the workshop popularity scorer needs to compare the assignments to the preferences, but the preset students don't have any preferences. This may get fixed once we use the new Student class.

My current changes just copy lines from the presets sheet to the output sheet. Using the new classes instead will help track workshop capacity.

**Comment by beszel** [comment]
This feature has been added.
